=== aladac/dubs/data/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/saiden-dev/dubs/data/schema.json",
  "title": "Dubs Theme",
  "description": "Theme definition for the dubs name generator",
  "type": "object",
  "required": ["name", "display_name", "categories", "default_category"],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9-]*$",
      "description": "Machine-readable theme identifier (lowercase, hyphens allowed)"
    },
    "display_name": {
      "type": "string",
      "description": "Human-readable theme name"
    },
    "categories": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string",
          "pattern": "^[a-z0-9][a-z0-9-]*$"
        }
      },
      "description": "Named lists of nouns. Keys are category names, values are arrays of slugified nouns."
    },
    "default_category": {
      "type": "string",
      "description": "Must reference an existing key in categories"
    }
  }
}

=== aladac/dubs/data/themes/transformers.json
{
  "name": "transformers",
  "display_name": "Transformers",
  "categories": {
    "autobots": [
      "bumblebee", "cliffjumper", "elita-one", "grimlock", "hoist",
      "hound", "ironhide", "jazz", "jetfire", "mirage",
      "optimus", "perceptor", "prowl", "ratchet", "rodimus",
      "sideswipe", "silverbolt", "skyfire", "smokescreen", "springer",
      "sunstreaker", "trailbreaker", "ultra-magnus", "wheeljack", "windcharger"
    ],
    "decepticons": [
      "astrotrain", "barricade", "blitzwing", "bonecrusher", "breakdown",
      "cyclonus", "devastator", "dirge", "galvatron", "kickback",
      "laserbeak", "megatron", "mixmaster", "motormaster", "ramjet",
      "ravage", "rumble", "scavenger", "scorponok", "seekers",
      "shockwave", "skywarp", "soundwave", "starscream", "thundercracker",
      "trypticon"
    ],
    "combiners": [
      "abominus", "bruticus", "computron", "defensor", "devastator",
      "elita-infin1t", "liokaiser", "menasor", "piranacon",
      "predaking", "ruination", "superion", "volcanicus"
    ]
  },
  "default_category": "autobots"
}

=== aladac/dubs/data/themes/nato.json
{
  "name": "nato",
  "display_name": "NATO",
  "categories": {
    "phonetic": [
      "alfa",
      "bravo",
      "charlie",
      "delta",
      "echo",
      "foxtrot",
      "golf",
      "hotel",
      "india",
      "juliet",
      "kilo",
      "lima",
      "mike",
      "november",
      "oscar",
      "papa",
      "quebec",
      "romeo",
      "sierra",
      "tango",
      "uniform",
      "victor",
      "whiskey",
      "xray",
      "yankee",
      "zulu"
    ],
    "operations": [
      "anvil",
      "avalanche",
      "barbarossa",
      "bayonet",
      "brimstone",
      "citadel",
      "crossbow",
      "dagger",
      "dragoon",
      "eagle",
      "falcon",
      "gladiator",
      "hammerfall",
      "husky",
      "ironclad",
      "kremlin",
      "mace",
      "neptune",
      "overlord",
      "pegasus",
      "quicksilver",
      "sabre",
      "tempest",
      "trident",
      "urgent-fury",
      "valkyrie",
      "warhammer",
      "anaconda",
      "atlas",
      "bandit",
      "bastion",
      "blizzard",
      "bulldog",
      "condor",
      "crusader",
      "demon",
      "eclipse",
      "ember",
      "firestorm",
      "fortress",
      "genesis",
      "griffin",
      "havoc",
      "inferno",
      "jaguar",
      "lightning",
      "mongoose",
      "musket",
      "nightfall",
      "ocelot",
      "paladin",
      "phantom",
      "python",
      "raven",
      "stalker",
      "stingray",
      "talon",
      "thunder",
      "titan",
      "vanguard",
      "venom",
      "vigilant",
      "vulcan",
      "wolfpack",
      "barracuda",
      "cardinal",
      "cyclone",
      "firebolt",
      "gryphon",
      "hammer",
      "ironside",
      "longbow",
      "mantis",
      "nighthawk",
      "panther",
      "rampart",
      "sandstorm",
      "siege",
      "stormfront",
      "torpedo",
      "uppercut",
      "viper",
      "warlock",
      "zenith"
    ],
    "ranks": [
      "admiral",
      "brigadier",
      "captain",
      "colonel",
      "commander",
      "commodore",
      "corporal",
      "ensign",
      "general",
      "lieutenant",
      "major",
      "marshal",
      "private",
      "sergeant",
      "warrant",
      "cadet",
      "centurion",
      "chief",
      "conscript",
      "deputy",
      "field-marshal",
      "gunner",
      "lancer",
      "midshipman",
      "officer",
      "petty-officer",
      "quartermaster",
      "ranger",
      "recruit",
      "sentinel",
      "specialist",
      "strategist",
      "subaltern",
      "trooper",
      "veteran"
    ],
    "equipment": [
      "abrams",
      "apache",
      "blackhawk",
      "bradley",
      "chinook",
      "cobra",
      "comanche",
      "f-16",
      "f-22",
      "f-35",
      "globemaster",
      "harrier",
      "hercules",
      "humvee",
      "kiowa",
      "lav",
      "leopard",
      "linebacker",
      "osprey",
      "patriot",
      "predator",
      "raptor",
      "reaper",
      "stinger",
      "stryker",
      "tomahawk",
      "tornado",
      "typhoon",
      "viper",
      "warthog",
      "abbot",
      "ajax",
      "archer",
      "boxer",
      "caesar",
      "challenger",
      "cougar",
      "foxhound",
      "grizzly",
      "guardian",
      "howitzer",
      "javelin",
      "leclerc",
      "mantis",
      "marder",
      "merkava",
      "mortar",
      "panther",
      "piranha",
      "puma",
      "scorpion",
      "scimitar",
      "spartan",
      "stormer",
      "warrior"
    ]
  },
  "default_category": "phonetic"
}

=== aladac/dubs/data/themes/fallout.json
{
  "name": "fallout",
  "display_name": "Fallout",
  "categories": {
    "creatures": [
      "angler",
      "assaultron",
      "behemoth",
      "bloatfly",
      "bloodbug",
      "brahmin",
      "cazador",
      "centaur",
      "crawling-torso",
      "crickets",
      "deathclaw",
      "eyebot",
      "feral-ghoul",
      "floater",
      "fog-crawler",
      "gatorclaw",
      "gecko",
      "ghoul",
      "grafton-monster",
      "gulper",
      "hermit-crab",
      "honeybeasts",
      "humanoid-robot",
      "liberator",
      "megasloth",
      "mirelurk",
      "mirelurk-queen",
      "mole-rat",
      "mongrel",
      "mothman",
      "mutant-hound",
      "nightstalker",
      "protectron",
      "radroach",
      "radscorpion",
      "radstag",
      "radtoad",
      "robobrain",
      "scorchbeast",
      "scorchbeast-queen",
      "sentry-bot",
      "sheepsquatch"
    ],
    "factions": [
      "atom-cats",
      "bos",
      "boomers",
      "caesars-legion",
      "children-of-atom",
      "brotherhood-outcasts",
      "crater-raiders",
      "disciples",
      "enclave",
      "fire-breathers",
      "followers",
      "foundation-settlers",
      "free-states",
      "great-khans",
      "gunners",
      "institute",
      "khans",
      "minutemen",
      "mister-house",
      "mothman-cultists",
      "ncr",
      "nuka-world-raiders",
      "operators",
      "pack",
      "powder-gangers",
      "railroad",
      "raiders",
      "regulators",
      "responders",
      "zetans",
      "talon-company",
      "the-kings",
      "tunnel-snakes",
      "vault-tec",
      "white-glove-society"
    ],
    "locations": [
      "acadia",
      "big-mt",
      "boston-common",
      "bunker-hill",
      "cambridge",
      "camp-mccarran",
      "camp-searchlight",
      "concord",
      "corvega",
      "diamond-city",
      "far-harbor",
      "fenway",
      "fort-hagen",
      "fort-independence",
      "freeside",
      "goodneighbor",
      "goodsprings",
      "grayditch",
      "helios-one",
      "hoover-dam",
      "jacobstown",
      "lexington",
      "lucky-38",
      "mariposa",
      "mass-fusion",
      "megaton",
      "necropolis",
      "nellis-afb",
      "new-vegas",
      "novac",
      "nuka-world",
      "oasis",
      "paradise-falls",
      "primm",
      "quincy",
      "red-rocket",
      "rivet-city",
      "salem",
      "sanctuary-hills",
      "shady-sands",
      "spectacle-island",
      "tenpenny-tower",
      "the-castle",
      "the-citadel",
      "the-commonwealth",
      "the-divide",
      "the-glowing-sea",
      "the-hub",
      "the-pitt",
      "the-strip"
    ],
    "weapons": [
      "10mm-pistol",
      "alien-blaster",
      "anti-materiel-rifle",
      "assault-rifle",
      "bb-gun",
      "big-boy",
      "broadsider",
      "bumper-sword",
      "chinese-assault",
      "combat-shotgun",
      "cryolator",
      "deliverer",
      "fatman",
      "fist-of-rawr",
      "flamer",
      "gamma-gun",
      "gauss-rifle",
      "gatling-laser",
      "hunting-rifle",
      "junk-jet",
      "kelloggs-pistol",
      "kremvhs-tooth",
      "laser-musket",
      "laser-rifle",
      "lincoln-repeater",
      "minigun",
      "mirv",
      "missile-launcher",
      "nuka-nuke",
      "overseer-guardian",
      "plasma-caster",
      "plasma-rifle",
      "power-fist",
      "radium-rifle",
      "railway-rifle",
      "ripper",
      "rock-it-launcher",
      "shishkebab",
      "sledgehammer",
      "spray-n-pray",
      "submachine-gun",
      "super-sledge"
    ],
    "characters": [
      "arcade-gannon",
      "boone",
      "butch",
      "cait",
      "cassidy",
      "charon",
      "codsworth",
      "curie",
      "danse",
      "deacon",
      "dogmeat",
      "ed-e",
      "elder-lyons",
      "elder-maxson",
      "fawkes",
      "hancock",
      "lily",
      "macready",
      "madison-li",
      "moira-brown",
      "mr-house",
      "nick-valentine",
      "piper",
      "preston",
      "raul",
      "rex",
      "strong",
      "three-dog",
      "ulysses",
      "veronica",
      "yes-man"
    ]
  },
  "default_category": "creatures"
}

=== aladac/dubs/data/themes/eveonline.json
{
  "name": "eveonline",
  "display_name": "EVE Online",
  "categories": {
    "ships": [
      "abaddon",
      "absolution",
      "algos",
      "apocalypse",
      "arazu",
      "archon",
      "armageddon",
      "astero",
      "atron",
      "avatar",
      "badger",
      "bantam",
      "barghest",
      "basilisk",
      "bellicose",
      "bifrost",
      "blackbird",
      "broadsword",
      "brutix",
      "bustard",
      "caracal",
      "catalyst",
      "cerberus",
      "chimera",
      "claymore",
      "coercer",
      "condor",
      "confessor",
      "corax",
      "cormorant",
      "crane",
      "crow",
      "crucifier",
      "cyclone",
      "damnation",
      "damavik",
      "deimos",
      "devoter",
      "dominix",
      "drake",
      "dramiel",
      "eagle",
      "enyo",
      "erebus",
      "exequror",
      "ferox",
      "firetail",
      "flycatcher",
      "gnosis",
      "golem",
      "gila",
      "harbinger",
      "harpy",
      "hawk",
      "hecate",
      "hel",
      "heron",
      "hookbill",
      "huginn",
      "hurricane",
      "hyperion",
      "ibis",
      "impairor",
      "impel",
      "incursus",
      "ishkur",
      "ishtar",
      "jackdaw",
      "jaguar",
      "keres",
      "kestrel",
      "kikimora",
      "kronos",
      "lachesis",
      "legion",
      "leviathan",
      "loki",
      "machariel",
      "maelstrom",
      "magnate",
      "maller",
      "malediction",
      "manticore",
      "mastodon",
      "megathron",
      "merlin",
      "moa",
      "moros",
      "muninn",
      "myrmidon",
      "naga",
      "naglfar",
      "nemesis",
      "nidhoggur",
      "nightmare",
      "nyx",
      "omen",
      "oneiros"
    ],
    "factions": [
      "amarr",
      "caldari",
      "gallente",
      "minmatar",
      "angel-cartel",
      "blood-raiders",
      "concord",
      "guristas",
      "mordu",
      "ore",
      "sansha",
      "serpentis",
      "sisters-of-eve",
      "society-of-ct",
      "thukker",
      "triglavian",
      "edencom",
      "drifters",
      "jovian",
      "upwell",
      "intaki",
      "khanid",
      "ammatar",
      "interbus",
      "outer-ring-excavations",
      "wiyrkomi",
      "lai-dai",
      "ishukone",
      "kaalakiota",
      "hyasyoda"
    ],
    "regions": [
      "aridia",
      "black-rise",
      "branch",
      "cache",
      "catch",
      "cloud-ring",
      "cobalt-edge",
      "curse",
      "deklein",
      "delve",
      "detorid",
      "devoid",
      "domain",
      "esoteria",
      "essence",
      "etherium-reach",
      "fade",
      "feythabolis",
      "fountain",
      "geminate",
      "genesis",
      "great-wildlands",
      "heimatar",
      "immensea",
      "impass",
      "insmother",
      "lonetrek",
      "malpais",
      "metropolis",
      "molden-heath",
      "outer-passage",
      "outer-ring",
      "paragon-soul",
      "period-basis",
      "perrigen-falls",
      "placid",
      "providence",
      "pure-blind",
      "querious",
      "scalding-pass",
      "sinq-laison",
      "solitude",
      "stain",
      "syndicate",
      "tash-murkon",
      "tenal",
      "the-bleak-lands",
      "the-citadel"
    ],
    "systems": [
      "amamake",
      "asakai",
      "b-r5rb",
      "ec-p8r",
      "heydeles",
      "huola",
      "jita",
      "kamela",
      "m-oee8",
      "old-man-star",
      "poitot",
      "rancer",
      "tama",
      "thera",
      "uedama",
      "dodixie",
      "hek",
      "rens",
      "perimeter",
      "niarja",
      "ahbazon",
      "oulley",
      "misaba",
      "keberz"
    ]
  },
  "default_category": "ships"
}

=== aladac/dubs/data/themes/pokemon.json
{
  "name": "pokemon",
  "display_name": "Pokémon",
  "categories": {
    "gen1": [
      "abra",
      "aerodactyl",
      "alakazam",
      "arcanine",
      "articuno",
      "blastoise",
      "bulbasaur",
      "chansey",
      "charizard",
      "charmander",
      "clefairy",
      "cubone",
      "dewgong",
      "diglett",
      "ditto",
      "dodrio",
      "dragonite",
      "drowzee",
      "dugtrio",
      "eevee",
      "electabuzz",
      "electrode",
      "exeggcute",
      "farfetchd",
      "fearow",
      "flareon",
      "gastly",
      "gengar",
      "geodude",
      "golduck",
      "golem",
      "graveler",
      "grimer",
      "growlithe",
      "gyarados",
      "haunter",
      "hitmonchan",
      "hitmonlee",
      "hypno",
      "ivysaur",
      "jigglypuff",
      "jolteon",
      "jynx",
      "kabuto",
      "kabutops",
      "kadabra",
      "kangaskhan",
      "kingler",
      "koffing",
      "lapras",
      "lickitung",
      "machamp",
      "machoke",
      "magikarp",
      "magmar",
      "magnemite",
      "magneton",
      "mankey",
      "marowak",
      "meowth",
      "mewtwo",
      "mew",
      "moltres",
      "mr-mime",
      "muk",
      "nidoking",
      "nidoqueen",
      "ninetales",
      "oddish",
      "omanyte",
      "onix",
      "parasect",
      "persian",
      "pidgeot",
      "pikachu",
      "pinsir",
      "poliwrath",
      "ponyta",
      "porygon",
      "primeape",
      "psyduck",
      "rapidash",
      "rhydon",
      "sandslash",
      "scyther"
    ],
    "legendaries": [
      "arceus",
      "azelf",
      "calyrex",
      "celebi",
      "cobalion",
      "cresselia",
      "darkrai",
      "deoxys",
      "dialga",
      "entei",
      "eternatus",
      "genesect",
      "giratina",
      "groudon",
      "heatran",
      "ho-oh",
      "jirachi",
      "keldeo",
      "koraidon",
      "kyogre",
      "kyurem",
      "landorus",
      "latias",
      "latios",
      "lugia",
      "lunala",
      "manaphy",
      "marshadow",
      "meloetta",
      "mesprit",
      "miraidon",
      "necrozma",
      "palkia",
      "raikou",
      "rayquaza",
      "regice",
      "regigigas",
      "regirock",
      "registeel",
      "reshiram",
      "shaymin",
      "solgaleo",
      "suicune",
      "terrakion",
      "thundurus",
      "tornadus",
      "uxie",
      "victini",
      "virizion",
      "volcanion",
      "xerneas",
      "yveltal",
      "zacian",
      "zamazenta",
      "zekrom",
      "zeroara",
      "zygarde"
    ],
    "types": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "regions": [
      "alola",
      "galar",
      "hoenn",
      "johto",
      "kalos",
      "kanto",
      "kitakami",
      "paldea",
      "sinnoh",
      "unova"
    ],
    "items": [
      "antidote",
      "dawn-stone",
      "dusk-ball",
      "escape-rope",
      "ether",
      "everstone",
      "exp-share",
      "fire-stone",
      "full-restore",
      "great-ball",
      "hyper-potion",
      "leaf-stone",
      "lemonade",
      "lucky-egg",
      "master-ball",
      "max-elixir",
      "max-revive",
      "moon-stone",
      "nugget",
      "poke-ball",
      "potion",
      "pp-up",
      "quick-ball",
      "rare-candy",
      "repel",
      "revive",
      "sacred-ash",
      "sun-stone",
      "thunder-stone",
      "timer-ball"
    ]
  },
  "default_category": "gen1"
}

=== aladac/dubs/data/themes/leet.json
{
  "name": "leet",
  "display_name": "1337 Speak",
  "categories": {
    "handles": [
      "0day",
      "0v3rf10w",
      "1337",
      "b0t",
      "b4ckd00r",
      "b1n4ry",
      "bl4ckh4t",
      "c0d3r",
      "c0mpl13r",
      "cr4ck",
      "cr4ck3r",
      "crypt0",
      "cyb0rg",
      "d34dm4n",
      "d3bug",
      "d4rkl0rd",
      "d4rkn3t",
      "d4rkw3b",
      "fl00d",
      "gh0st",
      "gl1tch",
      "gr1ml0ck",
      "h4x0r",
      "k3rn3l",
      "l0g1c",
      "m4lw4r3",
      "m4tr1x",
      "m4v3r1ck",
      "n00b",
      "n3tw0rk",
      "n1ghtf0x",
      "n1tr0",
      "null",
      "p4ck3t",
      "p4yl04d",
      "ph34r",
      "ph4nt0m",
      "pr0c3ss",
      "pr0xy",
      "pwn4g3",
      "r00t",
      "r00tk1t",
      "r3b00t",
      "r3c0n",
      "s0ck3t",
      "sc4nn3r",
      "scr1pt",
      "sh3ll",
      "sk1llz",
      "sk1nn3r",
      "sn1ff3r",
      "sp00f",
      "sp4wn",
      "t3rm1n4l",
      "tr0j4n",
      "v1rus",
      "v3ct0r",
      "w0rm",
      "x0r",
      "z0mb13",
      "z3r0d4y",
      "b4ckf1r3",
      "c1ph3r",
      "d4t4",
      "f1r3w4ll",
      "h0n3yp0t"
    ],
    "actions": [
      "b4sh",
      "bl4st",
      "br34k",
      "br3wt",
      "buff3r",
      "buc3",
      "cr4ck-act",
      "cr4sh",
      "crypt",
      "d3c0d3",
      "d3l3t3",
      "d3str0y",
      "d3f4c3",
      "dump",
      "3nc0d3",
      "3scal8",
      "3x3c",
      "3xf1l",
      "3xpl01t",
      "fl4g",
      "fl4sh",
      "fr4g",
      "gr1nd",
      "h4ck",
      "h1j4ck",
      "1nj3ct",
      "j4ck",
      "k1ll",
      "l04d",
      "l0ck",
      "m0rph",
      "nuk3",
      "0bfusc8",
      "0wn",
      "p4rs3",
      "p4tch",
      "p1ng",
      "pwn",
      "r3kt",
      "r3v3rs3",
      "r3wr1t3",
      "s4n1t1z3",
      "sc4n",
      "sh1ft",
      "sn1ff",
      "spl01t",
      "sp4m",
      "sn1p3",
      "sp00f-act",
      "tr4c3"
    ],
    "ranks": [
      "0p",
      "4dm1n",
      "4rc4ng3l",
      "b0ss",
      "c4pt41n",
      "ch13f",
      "cr0wn",
      "d3m0n",
      "3l1t3",
      "g0d",
      "h1ghl4nd3r",
      "j3d1",
      "k1ng",
      "l34d",
      "l0rd",
      "m4st3r",
      "m4y0r",
      "n1nj4",
      "0v3rl0rd",
      "p4tr0n",
      "pr0",
      "r3g3nt",
      "r3p3r",
      "r00t-rank",
      "s4g3",
      "s3ntr1",
      "sh0gun",
      "sup3r",
      "t1t4n",
      "w1z4rd"
    ],
    "protocols": [
      "dn5",
      "ftp",
      "http",
      "https",
      "1cm9",
      "1rc",
      "k3rb3r0s",
      "ldap",
      "mqtt",
      "nfs",
      "nn7p",
      "ppp",
      "r4d1us",
      "rdp",
      "rsyn",
      "sm7p",
      "snmp",
      "ssh",
      "ssl",
      "t3ln3t",
      "tcp",
      "tls",
      "udp",
      "vnc",
      "vpn",
      "ws",
      "x11",
      "xmpp"
    ],
    "tools": [
      "burp",
      "c0b4lt",
      "d1rb",
      "h4shr4t",
      "h1dr4",
      "j0hn",
      "k4l1",
      "m3t4spl01t",
      "n1k70",
      "nm4p",
      "n3tc4t",
      "0w4sp",
      "p4ws",
      "r3sp0nd3r",
      "s3tl",
      "sn0rt",
      "sql1",
      "w1r3sh4rk",
      "z4p",
      "g0bust3r",
      "bl00dh0und",
      "4irp4ck",
      "ff0f",
      "b33f",
      "h4shc4t",
      "c4in"
    ]
  },
  "default_category": "handles"
}

=== aladac/dubs/data/themes/warhammer-40k.json
{
  "name": "warhammer-40k",
  "display_name": "Warhammer 40,000",
  "categories": {
    "chapters": [
      "alpha-legion",
      "black-legion",
      "black-templars",
      "blood-angels",
      "blood-ravens",
      "carcharodons",
      "crimson-fists",
      "dark-angels",
      "death-guard",
      "deathwatch",
      "emperor-children",
      "exorcists",
      "flesh-tearers",
      "grey-knights",
      "howling-griffons",
      "imperial-fists",
      "iron-hands",
      "iron-warriors",
      "lamenters",
      "minotaurs",
      "night-lords",
      "novamarines",
      "raptors",
      "raven-guard",
      "red-scorpions",
      "red-talons",
      "salamanders",
      "silver-skulls",
      "sons-of-medusa",
      "soul-drinkers",
      "space-wolves",
      "thousand-sons",
      "ultramarines",
      "white-scars",
      "word-bearers",
      "world-eaters"
    ],
    "units": [
      "assault-marine",
      "baneblade",
      "basilisk",
      "berzerker",
      "bladeguard",
      "carnifex",
      "centurion",
      "chaplain",
      "chimera",
      "crisis-suit",
      "custodes",
      "deathmark",
      "devastator",
      "dire-avenger",
      "dreadnought",
      "eradicator",
      "exarch",
      "falcon",
      "fire-dragon",
      "fire-warrior",
      "flayed-one",
      "genestealer",
      "ghost-ark",
      "guardian",
      "havoc",
      "hellblaster",
      "helldrake",
      "howling-banshee",
      "immortal",
      "incubus",
      "intercessor",
      "kabalite",
      "knight",
      "land-raider",
      "leman-russ",
      "librarian",
      "lychguard",
      "mandrake",
      "monolith",
      "necron-warrior",
      "obliterator",
      "pathfinder",
      "plague-marine",
      "predator",
      "primaris",
      "raider",
      "ravener",
      "razorback",
      "reiver",
      "repulsor",
      "rhino",
      "rubric-marine",
      "sentinel",
      "seraphim",
      "shadowseer",
      "sister-of-battle",
      "skorpekh",
      "stormraven",
      "striking-scorpion",
      "swooping-hawk",
      "techmarine",
      "terminator",
      "thunderhawk",
      "tomb-blade",
      "triarch-praetorian",
      "tyranid-warrior",
      "valkyrie",
      "vindicator",
      "warboss",
      "warp-spider"
    ],
    "primarchs": [
      "alpharius",
      "angron",
      "corvus-corax",
      "dorn",
      "ferrus-manus",
      "fulgrim",
      "guilliman",
      "horus",
      "jaghatai-khan",
      "konrad-curze",
      "leman-russ-primarch",
      "lion-el-jonson",
      "lorgar",
      "magnus",
      "mortarion",
      "omegon",
      "perturabo",
      "rogal-dorn",
      "roboute",
      "sanguinius",
      "vulkan"
    ],
    "gods": [
      "emperor",
      "khorne",
      "nurgle",
      "slaanesh",
      "tzeentch",
      "cegorach",
      "gork",
      "isha",
      "khaine",
      "mork",
      "ynnead"
    ],
    "weapons": [
      "autocannon",
      "boltgun",
      "boltstorm",
      "chainfist",
      "chainsword",
      "daemon-sword",
      "eviscerator",
      "flamestorm",
      "force-sword",
      "gauss-flayer",
      "graviton",
      "heavy-bolter",
      "heavy-flamer",
      "inferno-pistol",
      "krak-grenade",
      "lascannon",
      "melta-bomb",
      "meltagun",
      "multi-melta",
      "phase-sword",
      "plasma-cannon",
      "plasma-gun",
      "plasma-pistol",
      "power-axe",
      "power-claw",
      "power-fist",
      "power-sword",
      "reaper-cannon",
      "shuriken-cannon",
      "splinter-rifle",
      "storm-bolter",
      "storm-shield",
      "tesla-carbine",
      "thunder-hammer",
      "void-blade",
      "volkite",
      "warp-blade"
    ],
    "vehicles": [
      "goliath",
      "hammerhead",
      "hellhound",
      "immolator",
      "knight-castellan",
      "knight-errant",
      "land-speeder",
      "leman-russ-tank",
      "malcador",
      "manticore",
      "mastodon",
      "night-scythe",
      "piranha",
      "raider-vehicle",
      "reaver-titan",
      "repulsor-executioner",
      "shadowsword",
      "stormbird",
      "stormlord",
      "stormraven-gunship",
      "stormsurge",
      "thunderhawk-gunship",
      "titan-warlord",
      "valkyrie-airship",
      "warhound-titan"
    ]
  },
  "default_category": "chapters"
}

=== aladac/dubs/data/themes/star-trek.json
{
  "name": "star-trek",
  "display_name": "Star Trek",
  "categories": {
    "ship_classes": [
      "akira",
      "ambassador",
      "california",
      "centaur",
      "cheyenne",
      "constellation",
      "constitution",
      "crossfield",
      "danube",
      "defiant",
      "dreadnought",
      "excelsior",
      "freedom",
      "galaxy",
      "hermes",
      "inquiry",
      "intrepid",
      "kelvin",
      "luna",
      "miranda",
      "nebula",
      "new-orleans",
      "niagara",
      "norway",
      "nova",
      "oberth",
      "odyssey",
      "olympic",
      "pathfinder",
      "prometheus",
      "ptolemy",
      "reliant",
      "saber",
      "sovereign",
      "springfield",
      "steamrunner",
      "sydney",
      "vesta",
      "walker"
    ],
    "species": [
      "andorian",
      "bajoran",
      "benzite",
      "betazoid",
      "bolian",
      "borg",
      "breen",
      "caitian",
      "cardassian",
      "changeling",
      "denobulan",
      "deltan",
      "edosian",
      "ferengi",
      "founders",
      "gorn",
      "hirogen",
      "horta",
      "jem-hadar",
      "kazon",
      "kelpien",
      "klingon",
      "lurian",
      "nausicaan",
      "orion",
      "pakled",
      "reman",
      "rigelian",
      "romulan",
      "saurian",
      "sheliak",
      "species-8472",
      "suliban",
      "talaxian",
      "tellarite",
      "tholian",
      "trill",
      "undine",
      "vidiian",
      "vorta",
      "vulcan",
      "xindi",
      "el-aurian",
      "bynars",
      "efrosian",
      "zakdorn",
      "acamarian",
      "arcadian",
      "argelian",
      "chalnoth",
      "dopterian",
      "elaysian"
    ],
    "characters": [
      "archer",
      "bashir",
      "beverly",
      "boimler",
      "burnham",
      "chakotay",
      "chapel",
      "chekov",
      "crusher",
      "dax",
      "data",
      "doctor",
      "dukat",
      "freeman",
      "garak",
      "geordi",
      "guinan",
      "hugh",
      "janeway",
      "kim",
      "kira",
      "kirk",
      "laforge",
      "lorca",
      "mariner",
      "mccoy",
      "neelix",
      "nhan",
      "number-one",
      "obrien",
      "odo",
      "paris",
      "picard",
      "pike",
      "phlox",
      "q",
      "quark",
      "reed",
      "riker",
      "ro-laren",
      "saru",
      "scotty",
      "seven",
      "shaxs",
      "sisko",
      "spock",
      "stamets",
      "sulu",
      "tendi",
      "tilly",
      "torres",
      "tpol",
      "troi",
      "tuvok",
      "uhura",
      "weyoun",
      "worf",
      "yar"
    ],
    "ships": [
      "aventine",
      "bozeman",
      "cerritos",
      "dauntless",
      "defiant-nx",
      "discovery",
      "enterprise",
      "enterprise-b",
      "enterprise-c",
      "enterprise-d",
      "enterprise-e",
      "excelsior-ncc",
      "farragut",
      "grissom",
      "hood",
      "lakota",
      "lexington",
      "melbourne",
      "pasteur",
      "phoenix",
      "protostar",
      "raven",
      "reliant-ncc",
      "rio-grande",
      "saratoga",
      "shenzhou",
      "stargazer",
      "titan",
      "valiant",
      "vengeance",
      "voyager",
      "yeager",
      "zheng-he"
    ],
    "locations": [
      "bajor",
      "cardassia",
      "deep-space-nine",
      "earth",
      "earth-spacedock",
      "ferenginar",
      "memory-alpha",
      "nimbus-iii",
      "qonos",
      "remus",
      "risa",
      "romulus",
      "rura-penthe",
      "sha-ka-ree",
      "starbase-1",
      "talos-iv",
      "utopia-planitia",
      "wolf-359"
    ]
  },
  "default_category": "ship_classes"
}
